### ISSUE TITLE
Apply simple responsive design

### ISSUE THREAD

**Issue by reneviering** [codemade/caffeine#37]
Apply simple design like this screen:
![desktop copy](https://cloud.githubusercontent.com/assets/6024397/10123528/1127e95a-653c-11e5-99c2-903775cba379.png)

"Links neben dem Intensity filter hätte man theoretisch dann sogar noch platz für ne Text-Suche, falls das zu leer wirkt."

"Mache dann nur 2 responsive Abstufungen: Smartphone und Desktop; alles darunter sieht aus wie Smartphone."

"Stelle denn auf dem Smartphone nur das Shopping-Symbol dar, keine Details."

**Comment by chrkhl** [comment]
Excellent work! :+1:
