### ISSUE TITLE
React, FLUX & Co. 

### ISSUE THREAD

**Issue by reneviering** [codemade/caffeine#8]
Collection of links about flux:
- https://facebook.github.io/flux/docs/overview.html#content
- http://de.slideshare.net/xmlilley/react-flux-50660816
- http://martyjs.org/guides/flux/
- http://stackoverflow.com/questions/23591325/in-flux-architecture-how-do-you-manage-store-lifecycle
- https://medium.com/brigade-engineering/what-is-the-flux-application-architecture-b57ebca85b9e
- https://madebymany.com/blog/beyond-the-to-do-app-writing-complex-applications-using-flux-react-js
- https://blog.andyet.com/2015/08/06/what-the-flux-lets-redux
- http://devangelist.de/facebook-flux-react/
- http://stackoverflow.com/questions/29350840/flux-pattern-to-initialize-store
- https://blog.rotenberg.io/flux-over-the-wire-3/
- http://blog.andrewray.me/flux-for-stupid-people/
- http://christianalfoni.github.io/javascript/2014/11/02/flux-with-angular-revisited.html
- http://stackoverflow.com/questions/27368907/how-to-use-flux-stores
- http://blogs.atlassian.com/2014/08/flux-architecture-step-by-step/

**Comment by chrkhl** [comment]
Introduction to React.js: https://youtu.be/XxVg_s8xAms

**Comment by chrkhl** [comment]
[react notes.txt](https://github.com/codemade/caffeine/files/15468/react.notes.txt)
[flux-notes.txt](https://github.com/codemade/caffeine/files/15469/flux-notes.txt)

[react-agenda.txt](https://github.com/codemade/caffeine/files/15470/react-agenda.txt)
[flux-agenda.txt](https://github.com/codemade/caffeine/files/15471/flux-agenda.txt)

**Comment by reneviering** [comment]
[flux.txt](https://github.com/codemade/caffeine/files/15499/flux.txt)

[ReactJS.txt](https://github.com/codemade/caffeine/files/15500/ReactJS.txt)

**Comment by reneviering** [comment]
Possible background images for the flux presentation:
https://www.flickr.com/search/?text=back%20in%20the%20future&license=4%2C5%2C9%2C10
